import game
import puzzleWin
import puzzle
import mainWinOnly
import pong
import main
import gameWinOnly
import customtkinter as tk
from PIL import Image
tk.set_appearance_mode("dark")
win=tk.CTk()
win.configure(bg="#0e142a")
win.geometry("850x600")
firstTime=0
def story():
    vict=mainWinOnly.runner()
    if vict:
        vict2=puzzleWin.runner()
        if vict2:
            vict3=gameWinOnly.runner(70)
            if vict3:
                pong.runner()
    quit()
def running():
    game.runner(70)
    quit()
def platforming():
    main.runner()
    quit()
def ponging():
    pong.runner()
    quit()
def typing():
    puzzle.runner()
    quit()
def first():
    login.pack_forget()
    signin.pack_forget()
    p1.pack()
    p2.pack_forget()
    begin.pack_forget()
def second():
    p2.pack()
    p1.pack_forget()
    begin.pack_forget()
def starting():
    begin.pack()
    user.pack_forget()
    p2.pack_forget()
    p1.pack_forget()
def loginShow():
    signin.pack_forget()
    begin.pack_forget()
    user.pack_forget()
    login.pack()
def signinShow():
    begin.pack_forget()
    user.pack_forget()
    signin.pack()
def userShow():
    begin.pack_forget()
    login.pack_forget()
    signin.pack_forget()
    user.pack()
p1=tk.CTkFrame(win,fg_color="#0e142a",bg_color="#0e142a")
p2=tk.CTkFrame(win,fg_color="#0e142a",bg_color='#0e142a')
begin=tk.CTkFrame(win,fg_color="transparent",bg_color="transparent")
login=tk.CTkFrame(win,fg_color="#0e142a",bg_color="#0e142a")
signin=tk.CTkFrame(win,fg_color="#0e142a",bg_color="#0e142a")
user=tk.CTkFrame(win,fg_color="#0e142a",bg_color="#0e142a")
box1=tk.CTkFrame(user,fg_color="transparent")
box2=tk.CTkFrame(login,fg_color="transparent",width=500)
box3=tk.CTkFrame(signin,fg_color="transparent",width=500)
box4=tk.CTkFrame(p1,fg_color="#0e142a")
topleft=tk.CTkFrame(p2,fg_color="#0e142a")
topright=tk.CTkFrame(p2,fg_color="#0e142a")
bottomleft=tk.CTkFrame(p2,fg_color="#0e142a")
bottomright=tk.CTkFrame(p2,fg_color="#0e142a")
beginside1=tk.CTkFrame(begin,fg_color="transparent",bg_color="transparent")
beginside2=tk.CTkFrame(begin,fg_color="transparent",bg_color="transparent")
left=tk.CTkFrame(p1,fg_color="transparent")
right=tk.CTkFrame(p1,fg_color="transparent")
img=Image.open("assets/icarus.png")
bg_img=Image.open("assets/beginning.png")
story_img=Image.open("images/story.png")
mini_img=Image.open("images/minigame.png")
start_img=Image.open("assets/start.png")
fly_img=Image.open("images/fly.png")
pong_img=Image.open("images/pong.png")
plat_img=Image.open("images/platform.png")
puzzle_img=Image.open("images/puzzle.png")
back1=tk.CTkButton(login, text="<",command=userShow, bg_color="transparent", fg_color="transparent",font=("courier",25),width=20,hover=False)
back2=tk.CTkButton(signin, text="<",command=userShow, bg_color="transparent", fg_color="transparent",font=("courier",25),width=20,hover=False)
#img=img.resize((50,50))
img=tk.CTkImage(light_image=img, dark_image=img, size=(50,50))
mini_img=tk.CTkImage(light_image=mini_img, dark_image=mini_img, size=(100,100))
story_img=tk.CTkImage(light_image=story_img, dark_image=story_img, size=(100,100))
start=tk.CTkImage(light_image=start_img, dark_image=start_img)
background=tk.CTkImage(light_image=bg_img, dark_image=bg_img, size=(850,600))
fly_img=tk.CTkImage(light_image=fly_img, dark_image=fly_img, size=(200,200))
puzzle_img=tk.CTkImage(light_image=puzzle_img, dark_image=puzzle_img, size=(200,200))
plat_img=tk.CTkImage(light_image=plat_img, dark_image=plat_img, size=(200,200))
pong_img=tk.CTkImage(light_image=pong_img, dark_image=pong_img, size=(200,200))
topleft.grid(column=0,row=0,pady=(40,50),padx=(175,30))
topright.grid(column=1,row=0,pady=(40,50),padx=(30,175))
bottomleft.grid(column=0,row=1,pady=(0,50),padx=(175,30))
bottomright.grid(column=1,row=1,pady=(0,50),padx=(30,175))
Name1=tk.CTkLabel(topleft,text="Runner Game:",font=("courier",23))
b1=tk.CTkButton(topleft, text="",command=running, image=fly_img, bg_color="transparent", fg_color="transparent",hover_color="#5c678b")
Name1.pack(anchor="center")
b1.pack(anchor="center")
Name2=tk.CTkLabel(topright,text="Pong Game:",font=("courier",23))
b2=tk.CTkButton(topright, text="",command=ponging, image=pong_img, bg_color="transparent", fg_color="transparent",hover_color="#5c678b")
Name2.pack(anchor="center")
b2.pack(anchor="center")
Name3=tk.CTkLabel(bottomleft,text="Platformer Game:",font=("courier",23))
b3=tk.CTkButton(bottomleft, text="",command=platforming, image=plat_img, bg_color="transparent", fg_color="transparent",hover_color="#5c678b")
Name3.pack(anchor="center")
b3.pack(anchor="center")
Name4=tk.CTkLabel(bottomright,text="Typing Game:",font=("courier",23))
b4=tk.CTkButton(bottomright, text="",command=typing, image=puzzle_img, bg_color="transparent", fg_color="transparent",hover_color="#5c678b")
Name4.pack(anchor="center")
b4.pack(anchor="center")
miniLabel=tk.CTkLabel(right,text="Mini Game Mode",font=("courier",23))
miniLabel.pack(pady=(0,20))
bHome1=tk.CTkButton(right, text="",command=second, image=mini_img, bg_color="transparent", fg_color="#0e142a",hover_color="#5c678b")
bHome1.pack()
storyLabel=tk.CTkLabel(left,text="Story Mode",font=("courier",23))
storyLabel.pack(pady=(0,20))
bHome2=tk.CTkButton(left, text="",command=story, image=story_img, bg_color="transparent", fg_color="transparent",hover_color="#5c678b",corner_radius=100)
bHome2.pack()
start=tk.CTkButton(beginside2,text="START",command=userShow, bg_color="transparent", fg_color="white",hover_color="#aab6d7",text_color="#0e142a",font=("courier",20))
loginB=tk.CTkButton(box1,text="LOGIN",command=loginShow, bg_color="#0e142a", fg_color="white",hover_color="#aab6d7",text_color="#0e142a",font=("courier",20))
signinB=tk.CTkButton(box1,text="SIGN UP",command=signinShow, bg_color="#0e142a", fg_color="white",hover_color="#aab6d7",text_color="#0e142a",font=("courier",20))
loginB.grid(row=0,column=0, padx=30,pady=300)
signinB.grid(row=0,column=1, padx=30,pady=300)
bg=tk.CTkLabel(beginside1,text="",image=background)
bg.pack()
start.pack()
back1.place(x=20,y=20)
back2.place(x=20,y=20)
box1.pack(padx=230)
#box4.pack()
left.grid(column=0,row=0,padx=(200,85),pady=(225,300))
right.grid(column=1,row=0,padx=(85,200),pady=(225,300))
beginside1.grid(row=0,column=0)
beginside2.grid(row=0,column=0,sticky="s",pady=100)
loginLabel=tk.CTkLabel(login,text="LOGIN",font=("courier",30))
loginLabel.pack(pady=(100,0))
signinLabel=tk.CTkLabel(signin,text="SIGN UP",font=("courier",30))
signinLabel.pack(pady=(100,0))
name1=tk.CTkLabel(box2,text="Username:",text_color="white",font=("courier",15))
pass1=tk.CTkLabel(box2,text="Password:",text_color="white",font=("courier",15))
nameE1=tk.CTkEntry(box2,fg_color="white",text_color="#0e142a",width=140)
passE1=tk.CTkEntry(box2,fg_color="white",text_color="#0e142a",width=200)
loginBu=tk.CTkButton(box2,text="SUBMIT" , bg_color="#0e142a", fg_color="white",text_color="#0e142a",font=("courier",20), command=first,hover_color="#aab6d7")
name2=tk.CTkLabel(box3,text="Username:",text_color="white",font=("courier",15))
pass2=tk.CTkLabel(box3,text="Password:",text_color="white",font=("courier",15))
signinBu=tk.CTkButton(box3,text="SUBMIT" , bg_color="#0e142a", fg_color="white",text_color="#0e142a",font=("courier",20), command=loginShow,hover_color="#aab6d7")
nameE2=tk.CTkEntry(box3,fg_color="white",text_color="#0e142a")
passE2=tk.CTkEntry(box3,fg_color="white",text_color="#0e142a")
box3.pack(padx=375,pady=(100,0))
box2.pack(padx=375,pady=(100,0))
name1.pack()
nameE1.pack()
pass1.pack()
passE1.pack()
loginBu.pack(pady=(30,200))
name2.pack()
nameE2.pack()
pass2.pack()
passE2.pack()
signinBu.pack(pady=(30,200))
starting()
win.mainloop()
